name: CO-Walk CI/CD - Nodejs CI with NPM and CD with Docker & AWS EC2

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      # 소스코드 다운로드
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      
      # Node.js 설정
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18.6.0'
          cache: 'npm'
      
      # npm install --force를 사용하여 종속성 설치
      - name: 종속성 설치
        run: npm install --force
      
      - run: npm run build --if-present
      
      # 환경 파일 설정
      - name: 환경 파일 설정
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env
        shell: bash
      
      # Node.js용 Docker 이미지 빌드
      - name: Node.js용 Docker 이미지 빌드
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:1.0 .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:1.0
      
      # EC2에서 Docker 실행
      - name: EC2 Docker 실행
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker stop eco-marketer
            docker rm eco-marketer
            docker rmi ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:1.0
            docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:1.0
            docker run -d -p 3000:3000 --name eco-marketer ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:1.0
